# Generated by Django 5.2.7 on 2025-10-13 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeatmapService',
            fields=[
                ('heatmap_id', models.UUIDField(primary_key=True, serialize=False)),
                ('area', models.CharField(max_length=100)),
                ('service_type', models.CharField(max_length=100)),
                ('intensity_score', models.FloatField()),
            ],
        ),
    ]
