# Generated by Django 5.2.7 on 2025-10-23 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaHeatmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=100, unique=True)),
                ('avg_price', models.FloatField(default=0)),
                ('color', models.CharField(default='#31a354', max_length=20)),
            ],
        ),
    ]
