# Generated by Django 5.2.7 on 2025-10-13 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PriceTrend',
            fields=[
                ('trend_id', models.UUIDField(primary_key=True, serialize=False)),
                ('area', models.CharField(max_length=100)),
                ('avg_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('popularity_score', models.FloatField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
