# Generated by Django 5.2.7 on 2025-10-22 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_delete_accountapprovalrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertydeleterequest',
            name='seen_by_requester',
            field=models.BooleanField(default=False, help_text='Requester has seen the final decision.'),
        ),
        migrations.AddField(
            model_name='propertyeditrequest',
            name='seen_by_requester',
            field=models.BooleanField(default=False, help_text='Requester has seen the final decision.'),
        ),
    ]
