# Generated by Django 5.2.7 on 2025-10-23 17:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_propertydeleterequest_seen_by_requester_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='negotiable',
            field=models.BooleanField(default=False, help_text='Allow renters to negotiate price via chat.'),
        ),
        migrations.CreateModel(
            name='Negotiation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is this negotiation still open?')),
                ('seen_by_landlord', models.BooleanField(default=False, help_text='Landlord has seen the latest message.')),
                ('seen_by_renter', models.BooleanField(default=False, help_text='Renter has seen the latest message.')),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_negotiations', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='negotiations', to='properties.property')),
                ('renter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='started_negotiations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('property', 'renter')},
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='The time the message was originally created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The time the message was last edited.')),
                ('is_edited', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
                ('negotiation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='properties.negotiation')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
