# Generated by Django 5.2.7 on 2025-10-16 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_is_approved_customuser_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_kyc_verified',
            field=models.BooleanField(default=False, help_text='Set to true when a user has an approved KYC document.'),
        ),
    ]
