# Generated by Django 5.2.7 on 2025-10-16 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_is_kyc_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(default='images/default.png', upload_to='profile_pics/'),
        ),
    ]
